// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/joejosephvarghese/message/server/pkg"
	"github.com/joejosephvarghese/message/server/pkg/api"
	"github.com/joejosephvarghese/message/server/pkg/api/middleware"
)

// Injectors from wire.go:

func InitializeAPI(cfg config.Config) (*api.Server, error) {
	middlewareMiddleware := middleware.NewMiddleware()
	server := api.NewServerHTTP(cfg, middlewareMiddleware)
	return server, nil
}
